services:

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  mongodb:
    image: mongo:8
    container_name: mongodb
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  signalr-hub:
    image: signalr-hub-service:latest
    container_name: signalr-hub
    ports:
      - "5177:8080"

  message-processing:
    image: message-processing-service:latest
    container_name: message-processing
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      signalr-hub:
        condition: service_started
    environment:
      RabbitMqConfig__HostName: rabbitmq
      RabbitMqConfig__Port: 5672
      RabbitMqConfig__UserName: guest
      RabbitMqConfig__Password: guest

      MongoDbConfig__ConnectionString: mongodb://mongodb:27017
      MongoDbConfig__DatabaseName: ServerMonitoring
      MongoDbConfig__CollectionName: ServerStatistics

      SignalRConfig__SignalRUrl: http://signalr-hub:8080/notificationHub

      AnomalyDetectionConfig__MemoryUsageAnomalyThresholdPercentage: 0.4
      AnomalyDetectionConfig__CpuUsageAnomalyThresholdPercentage: 0.5
      AnomalyDetectionConfig__MemoryUsageThresholdPercentage: 0.8
      AnomalyDetectionConfig__CpuUsageThresholdPercentage: 0.9

  server-monitoring:
    image: server-monitoring-service:latest
    container_name: server-monitoring
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      ServerStatisticsConfig__SamplingIntervalSeconds: 5
      ServerStatisticsConfig__ServerIdentifier: linux1

      RabbitMqConfig__HostName: rabbitmq
      RabbitMqConfig__Port: 5672
      RabbitMqConfig__UserName: guest
      RabbitMqConfig__Password: guest