<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-ServerMonitoringService-52554876-a1cd-4bbc-8e27-bc002375110f</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
        <PackageReference Include="RabbitMQ.Client" Version="7.2.2" />
        <PackageReference Include="System.Management" Version="10.0.11" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\RabbitMQClient\RabbitMQClient.csproj" />
    </ItemGroup>
</Project>
